version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: yowa_eshop_db
    environment:
      POSTGRES_USER: yowa_user
      POSTGRES_PASSWORD: yowa_pass
      POSTGRES_DB: yowa_eshop
    ports:
      - "5420:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: